version: "3.9"

services:
  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
    volumes:
      - prowlarr:/config
    restart: unless-stopped
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.prowlarr.rule=Host(`prowlarr.${BASE_DOMAIN}`)"
        - "traefik.http.routers.prowlarr.entrypoints=websecure"
        - "traefik.http.routers.prowlarr.tls.certresolver=dns"
        - "traefik.http.services.prowlarr.loadbalancer.server.port=9696"
    labels:
      - homepage.group=Downloads
      - homepage.name=Prowlarr
      - homepage.icon=prowlarr.png
      - homepage.href=https://prowlarr.${BASE_DOMAIN}/
      - homepage.description=Indexer Manager
      - homepage.widget.type=prowlarr
      - homepage.widget.url=https://prowlarr.${BASE_DOMAIN}/
      - homepage.widget.key=${PROWLARR_API_KEY}

networks:
  traefik-public:
    external: true

volumes:
  prowlarr:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=${SMB_USERNAME},password=${SMB_PASSWORD},domain=${SMB_DOMAIN},vers=3.0,file_mode=0600,dir_mode=0770"
      device: "//${NAS_SERVER}/prowlarr"
