version: "3"
services:
  reverseproxy:
    image: reverseproxy
    build:
      context: ./reverseproxy
      args:
        - TZ=America/New_York
    ports:
      - 80:80
      - 21064:21064
    restart: always
    networks:
      - reverseproxy
  emby:
    image: emby/embyserver:4.8.0.39
    container_name: embyserver
    environment:
      - UID=1000
      - GID=100
      - GIDLIST=100
    volumes:
      - ${PWD}/embyserver:/config
      - /media/external:/mnt/external
    ports:
      - 8096:8096
      - 8920:8920
    restart: on-failure
    depends_on:
      - reverseproxy
    networks:
      - reverseproxy

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${PWD}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8080:8080
    restart: unless-stopped
    privileged: true
    healthcheck:
      test: 'curl -m 90 -sLf http://0.0.0.0:8123 || date >> /config/healthcheck'
      interval: 90s
      timeout: 60s
      retries: 2
    networks:
      - reverseproxy

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${PWD}/radarr:/config
      - /media/external/media:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - reverseproxy
    networks:
      - reverseproxy

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - ${PWD}/sonarr:/config
      - /media/external/media:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - reverseproxy

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    volumes:
      - ${PWD}/deluge:/config
      - /media/external/media/torrents:/data/torrents
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - DELUGE_LOGLEVEL=info
    ports:
      - 8112:8112
    restart: unless-stopped
    networks:
      - reverseproxy

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - ${PWD}/qbittorrent:/config
      - /media/external/media/torrents:/data/torrents
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - reverseproxy

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${PWD}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - reverseproxy

networks:
  reverseproxy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
