version: "3"
services:
  reverseproxy:
    image: reverseproxy
    build:
      context: ./reverseproxy
      args:
        - TZ=America/New_York
    ports:
      - 80:80
      - 443:443
    volumes:
      - ${PWD}/rootCA.pem:/etc/nginx/ca.pem
      - ${PWD}/_wildcard.lab.local.pem:/etc/nginx/client.pem
      - ${PWD}/_wildcard.lab.local-key.pem:/etc/nginx/client.key
    restart: always
    networks:
      - reverseproxy

  actual_server:
    image: docker.io/actualbudget/actual-server:latest
    ports:
      # This line makes Actual available at port 5006 of the device you run the server on,
      # i.e. http://localhost:5006. You can change the first number to change the port, if you want.
      - '5006:5006'
    environment:
      - ACTUAL_HTTPS_KEY=/certs/selfhost.key
      - ACTUAL_HTTPS_CERT=/certs/selfhost.crt
      - ACTUAL_UPLOAD_FILE_SYNC_SIZE_LIMIT_MB=20
      - ACTUAL_UPLOAD_SYNC_ENCRYPTED_FILE_SYNC_SIZE_LIMIT_MB=50
      - ACTUAL_UPLOAD_FILE_SIZE_LIMIT_MB=20
      - DEBUG=actual:config
      # See all options and more details at https://actualbudget.github.io/docs/Installing/Configuration
    volumes:
      - /media/external/budget:/data
      - ${PWD}/_wildcard.lab.local-key.pem:/certs/selfhost.key
      - ${PWD}/_wildcard.lab.local.pem:/certs/selfhost.crt
    restart: unless-stopped
    depends_on:
      - reverseproxy
    networks:
      - reverseproxy

  portainer_agent:
    image: portainer/agent:2.19.4
    ports:
      - '9001:9001'
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock
      - /var/lib/docker/volumes:/var/lib/docker/volumes
    restart: always
    depends_on:
      - reverseproxy
    networks:
      - reverseproxy

  emby:
    image: emby/embyserver:4.9.0.4
    container_name: embyserver
    environment:
      - UID=1000
      - GID=100
      - GIDLIST=100
    volumes:
      - ${PWD}/embyserver:/config
      - /media/external:/mnt/external
    ports:
      - 8096:8096
      - 8920:8920
    restart: on-failure
    depends_on:
      - reverseproxy
    networks:
      - reverseproxy

  librechat:
    image: ghcr.io/danny-avila/librechat:v0.6.6
    container_name: LibreChat
    ports:
      - 3080:3080
    depends_on:
      - mongodb
      - reverseproxy
    restart: always
    user: "${UID}:${GID}"
    extra_hosts:
      - "host.docker.internal:host-gateway"
    env_file:
      - path: ./librechat/.env
        required: true
    volumes:
      - ./images:/app/client/public/images
    networks:
      - reverseproxy

  mongodb:
    container_name: chat-mongodb
    image: nertworkweb/mongodb-no-avx
    restart: always
    user: "${UID}:${GID}"
    ports:
      - 27017:27017
    volumes:
      - ./data-node:/data/db
    command: --noauth --bind_ip_all
    depends_on:
      - reverseproxy
    networks:
      - reverseproxy

  meilisearch:
    container_name: chat-meilisearch
    image: getmeili/meilisearch:v1.5
    restart: always
    user: "${UID}:${GID}"
    environment:
      - MEILI_HOST=http://meilisearch:7700
      - MEILI_NO_ANALYTICS=true
    volumes:
      - ./meili_data_v1.5:/meili_data
    depends_on:
      - reverseproxy
    networks:
      - reverseproxy

  homeassistant:
    container_name: homeassistant
    image: "ghcr.io/home-assistant/home-assistant:stable"
    volumes:
      - ${PWD}/homeassistant:/config
      - /etc/localtime:/etc/localtime:ro
    ports:
      - 8181:8181
    restart: unless-stopped
    privileged: true
    healthcheck:
      test: 'curl -m 90 -sLf http://0.0.0.0:8123 || date >> /config/healthcheck'
      interval: 90s
      timeout: 60s
      retries: 2
    depends_on:
      - reverseproxy
    networks:
      - reverseproxy

  radarr:
    image: lscr.io/linuxserver/radarr:latest
    container_name: radarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${PWD}/radarr:/config
      - /media/external/media:/data
    ports:
      - 7878:7878
    restart: unless-stopped
    depends_on:
      - reverseproxy
    networks:
      - reverseproxy

  sonarr:
    image: lscr.io/linuxserver/sonarr:latest
    container_name: sonarr
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - TZ=America/New_York
    volumes:
      - ${PWD}/sonarr:/config
      - /media/external/media:/data
    ports:
      - 8989:8989
    restart: unless-stopped
    networks:
      - reverseproxy

  deluge:
    image: lscr.io/linuxserver/deluge:latest
    container_name: deluge
    volumes:
      - ${PWD}/deluge:/config
      - /media/external/media/torrents:/data/torrents
    environment:
      - PUID=1000
      - PGID=1000
      - UMASK=002
      - DELUGE_LOGLEVEL=info
    ports:
      - 8112:8112
    restart: unless-stopped
    networks:
      - reverseproxy

  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
      - WEBUI_PORT=8080
    volumes:
      - ${PWD}/qbittorrent:/config
      - /media/external/media/torrents:/data/torrents
    ports:
      - 8080:8080
    restart: unless-stopped
    networks:
      - reverseproxy

  prowlarr:
    image: lscr.io/linuxserver/prowlarr:latest
    container_name: prowlarr
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=America/New_York
    volumes:
      - ${PWD}/prowlarr:/config
    ports:
      - 9696:9696
    restart: unless-stopped
    networks:
      - reverseproxy

networks:
  reverseproxy:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.31.0.0/16
