# ansible/roles/dns/tasks/adapters/pihole/remove-service-records.yml
---
- name: "[PIHOLE] Remove CNAME record for each service"
  ansible.builtin.uri:
    url: "{{ dns_secondary_api_url }}/config/dns/cnameRecords/{{ item }},{{ dns_manager_hostname | default(groups['managers'][0]) }}.{{ base_domain }},0?restart=false"
    method: DELETE
    headers:
      sid: "{{ dns_pihole_session_id }}"
    status_code: [200, 204, 404]
  loop: "{{ dns_discovered_domains }}"
  register: dns_pihole_remove_cname_result
  ignore_errors: yes
  delegate_to: localhost

- name: "[PIHOLE] Remove A record for Pi-hole host"
  ansible.builtin.uri:
    url: "{{ dns_secondary_api_url }}/config/dns/hosts/{{ secondary_dns_host }}%20pi.{{ base_domain }}"
    method: DELETE
    headers:
      sid: "{{ dns_pihole_session_id }}"
    status_code: [200, 204, 404]
  ignore_errors: yes
  delegate_to: localhost
  when: stack_name is defined and stack_name == 'dns'

- name: "[PIHOLE] Reload DNS resolver to drop the removed records"
  ansible.builtin.uri:
    url: "{{ dns_secondary_api_url }}/action/restartdns"
    method: POST
    headers:
      sid: "{{ dns_pihole_session_id }}"
    status_code: [200, 204]
  changed_when: false
  delegate_to: localhost
