# Multi-node homelab.yaml example
# Docker Compose with multiple machines
version: "2.0"
deployment: docker_compose

environment:
  BASE_DOMAIN: homelab.local
  PROJECT_ROOT: /opt/homelab
  TIMEZONE: America/New_York

machines:
  driver:
    host: 192.168.1.100
    user: ubuntu
  node-01:
    host: 192.168.1.101
    user: ubuntu
  node-02:
    host: 192.168.1.102
    user: ubuntu

services:
  # Infrastructure - deploy to all machines
  nginx:
    image: nginx:alpine
    ports: [80, 443]
    deploy: all

  # Management - deploy to driver only
  homepage:
    image: ghcr.io/gethomepage/homepage:latest
    port: 3000
    deploy: driver

  portainer:
    image: portainer/portainer-ce:latest
    port: 9000
    storage: true
    deploy: driver

  # Applications - specific machine deployment
  actual:
    image: actualbudget/actual-server:latest
    port: 5006
    storage: 5GB
    deploy: node-01

  homeassistant:
    image: ghcr.io/home-assistant/home-assistant:stable
    port: 8123
    storage: true
    deploy: node-02

  # Load balanced - let system choose
  jellyfin:
    image: jellyfin/jellyfin:latest
    port: 8096
    storage: 50GB
    deploy: random
