# Docker Swarm homelab.yaml example
# Advanced orchestration with placement constraints
version: "2.0"
deployment: docker_swarm

environment:
  BASE_DOMAIN: homelab.local
  PROJECT_ROOT: /opt/homelab
  SWARM_STACK_NAME: homelab

machines:
  driver:
    host: 192.168.1.100
    user: ubuntu
    role: manager
    labels:
      - storage=ssd
      - gpu=nvidia
  node-01:
    host: 192.168.1.101
    user: ubuntu
    role: worker
    labels:
      - storage=hdd
  node-02:
    host: 192.168.1.102
    user: ubuntu
    role: worker
    labels:
      - storage=ssd

services:
  # Global services (run on every node)
  nginx:
    image: nginx:alpine
    ports: [80, 443]
    deploy: all

  # Replicated services with scaling
  web_app:
    image: nginx:alpine
    port: 8080
    deploy: any
    overrides:
      docker_swarm:
        replicas: 3
        placement:
          constraints:
            - node.role == worker

  # Database with specific placement
  database:
    image: postgres:15
    port: 5432
    storage: 10GB
    deploy: driver
    environment:
      POSTGRES_PASSWORD: "${DB_PASSWORD}"
    overrides:
      docker_swarm:
        placement:
          constraints:
            - node.labels.storage == ssd

  # GPU workload
  ai_service:
    image: tensorflow/tensorflow:latest-gpu
    port: 8888
    deploy: driver
    overrides:
      docker_swarm:
        placement:
          constraints:
            - node.labels.gpu == nvidia
