version: "3.9"

services:
  qbittorrent:
    image: lscr.io/linuxserver/qbittorrent:latest
    container_name: qbittorrent
    environment:
      - PUID=1000
      - PGID=1000
      - TZ=${TZ}
      - WEBUI_PORT=8080
    volumes:
      - qbittorrent:/config
      - torrents:/data/torrents
    restart: unless-stopped
    networks:
      - traefik-public
    deploy:
      labels:
        - "traefik.enable=true"
        - "traefik.http.routers.qbittorrent.rule=Host(`qbittorrent.${BASE_DOMAIN}`)"
        - "traefik.http.routers.qbittorrent.entrypoints=websecure"
        - "traefik.http.routers.qbittorrent.tls.certresolver=dns"
        - "traefik.http.services.qbittorrent.loadbalancer.server.port=8080"
        - homepage.group=Downloads
        - homepage.name=qBittorrent
        - homepage.icon=qbittorrent.png
        - homepage.href=https://qbittorrent.${BASE_DOMAIN}/
        - homepage.description=Torrent Client
        - homepage.widget.type=qbittorrent
        - homepage.widget.url=https://qbittorrent.${BASE_DOMAIN}/
        - homepage.widget.username=${QBIT_USERNAME}
        - homepage.widget.password=${QBIT_PASSWORD}

networks:
  traefik-public:
    external: true

volumes:
  torrents:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=${SMB_USERNAME},password=${SMB_PASSWORD},domain=${SMB_DOMAIN},vers=3.0,file_mode=0600,dir_mode=0770"
      device: "//${NAS_SERVER}/torrents"

  qbittorrent:
    driver: local
    driver_opts:
      type: "cifs"
      o: "username=${SMB_USERNAME},password=${SMB_PASSWORD},domain=${SMB_DOMAIN},vers=3.0,file_mode=0600,dir_mode=0770"
      device: "//${NAS_SERVER}/qbittorrent"
